### ISSUE TITLE
Tor downloading error

### ISSUE THREAD

**Issue by Trusthoodies** [samet-g/tornado#3]
i get this error, can you please help?:
![afbeelding](https://user-images.githubusercontent.com/95029137/162791983-5667c6fe-5a59-4e62-8ef1-348b7671440f.png)

**Comment by Trusthoodies** [comment]
Thanks for your respondse!
Downloading tor works! so the new link works!
But now i get this error: [*] Failed to read tornado.raw :(
[*] Missing tornado.raw in pwd?

**Comment by Trusthoodies** [comment]
Did you receive my message?

**Comment by samet-g** [comment]
Yes, I did but I am not free right now. You can try WSL2 or linux machine for now. I will check later this windows integrity.
