### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by Chomikmarkus** [samet-g/tornado#5]
Hello!
System Ubuntu 20.04 x64
Install no errors, running sudo tornado i get next error
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in d
istribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in f
rom_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: tornado
root@ubuntu-s-2vcpu-4gb-ams3-01:/opt/tornado# sudo tornado start
Traceback (most recent call last):
  File "/usr/bin/tornado", line 33, in <module>
    sys.exit(load_entry_point('tornado==1.2', 'console_scripts',
'tornado')())
  File "/usr/bin/tornado", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.8/importlib/metadata.py", line 503, in d
istribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.8/importlib/metadata.py", line 177, in f
rom_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: tornado
root@ubuntu-s-2vcpu-4gb-ams3-01:/opt/tornado#
 
 
![Screenshot_20220525-234402_Admin Hands](https://user-images.githubusercontent.com/92059377/170363905-e14a2750-417b-46bd-98f9-e63d4c78f217.jpg)

**Comment by samet-g** [comment]
This issue not about tornado but you can try this commands.

`sudo pip3 uninstall setuptools`
`sudo pip3 install setuptools==60.9.3`

![image_2022-05-27_150234021](https://user-images.githubusercontent.com/81412659/170695660-e76dea36-5c48-48d2-9c31-c396fdab1517.png)

If this solution not works, I don't have any idea except of this but probably It will work!
