### ISSUE TITLE
TypeError: shell() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by HugoMskn** [samet-g/tornado#6]
Hi, 
So I was trying to run tornado on my kali laptop and I get this error 
![image](https://user-images.githubusercontent.com/81116453/174498019-bbb46b4a-fefa-4a87-b297-225f9b36fd1d.png)

I'm running this python version
![image](https://user-images.githubusercontent.com/81116453/174498037-eee718b9-b088-4eed-8ba2-967b4e7e3272.png)

**Comment by samet-g** [comment]
I solve the `TypeError: T0rnado.shell() takes 1 positional argument but 2 were given` problem and today I will update tornado with new torrc configuration function so It will be work very fine.
